apiVersion: v1
kind: Pod
metadata:
  name: pod-using-pvc
spec:
containers:
    - name: app
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-storage
volumes:
    - name: my-storage
      persistentVolumeClaim:
        claimName: my-pvc
